# Generated by Django 6.0.3 on 2026-04-18

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeFileSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("source_file_name", models.CharField(max_length=500)),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("runbook", "Runbook"),
                            ("threat_intelligence", "Threat Intelligence"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("summary_excerpt", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ("embedded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
    ]
