# Generated by Django 6.0.3 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0002_knowledgefilesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgefilesummary",
            name="source_url",
            field=models.URLField(blank=True),
        ),
    ]
