# Generated by Django 6.0.3 on 2026-03-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratorIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('was_stored', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wazuh_alert_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('wazuh_rule_id', models.CharField(db_index=True, max_length=64)),
                ('rule_level', models.PositiveSmallIntegerField(db_index=True)),
                ('rule_description', models.TextField()),
                ('rule_groups', models.JSONField(default=list)),
                ('rule_mitre', models.JSONField(default=dict)),
                ('agent_id', models.CharField(db_index=True, max_length=64)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('alert_timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-alert_timestamp'],
                'indexes': [models.Index(fields=['rule_level', 'alert_timestamp'], name='logs_alert_rule_le_b27006_idx'), models.Index(fields=['agent_id', 'alert_timestamp'], name='logs_alert_agent_i_38bd85_idx')],
            },
        ),
    ]
